### ISSUE TITLE
Unexpected error

### ISSUE THREAD

**Issue by lightning02** [RiskyKen/Cosmetic-Wings#5]
https://github.com/CreativeMD/RandomAdditions/issues/15#issuecomment-109037158

**Comment by RiskyKen** [comment]
gcewing is not cosmetic wings. I think it is Greg's Lighting, however I am not 100% sure.

http://www.cosc.canterbury.ac.nz/greg.ewing/minecraft/mods/GregsLighting/

**Comment by lightning02** [comment]
It may be Greg SG since I haven't geg's lighting installed.
